name: tracer-sidecar CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: sudo rm -rf /opt&
      - uses: actions/checkout@v4
      - uses: paolino/dev-assets/setup-nix@v0.0.1
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build executable
        working-directory: ./components/tracer-sidecar
        run: nix build .#tracer-sidecar
      - name: Build docker image
        run: nix build .#docker-image -o output-docker-image
        working-directory: ./components/tracer-sidecar
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cardano-utxo-csmt-image
          path: ./components/tracer-sidecar/output-docker-image
      - name: Build AppImage
        run: nix --quiet bundle --bundler github:ralismark/nix-appimage .#tracer-sidecar -o tracer-sidecar.AppImage
        working-directory: ./components/tracer-sidecar
      - name: Upload AppImage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tracer-sidecar-appimage
          path: ./components/tracer-sidecar/tracer-sidecar.AppImage
  unit:
    name: Run unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: paolino/dev-assets/setup-nix@v0.0.1
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Run Tests
        working-directory: ./components/tracer-sidecar
        run: nix run .#tracer-sidecar-tests
  # bench:
  #   name: Run Benchmarks
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: cachix/install-nix-action@v31
  #       with:
  #         extra_nix_config: |
  #           trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
  #           substituters = https://cache.iog.io https://cache.nixos.org/
  #           accept-flake-config = true
  #     - uses: cachix/cachix-action@v15
  #       with:
  #         name: paolino
  #         authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
  #     - name: Run Benchmarks
  #       run: nix run .#bench
  code-quality:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: paolino/dev-assets/setup-nix@v0.0.1
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Check Formatting
        working-directory: ./components/tracer-sidecar
        run: nix develop .#quality -c just format
      - name: Check linting
        working-directory: ./components/tracer-sidecar
        run: nix develop .#quality -c just hlint
